CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE SUBSCRIPTION (
  id  BIGINT NOT NULL PRIMARY KEY,
  amount DECIMAL(19,2) NOT NULL,
  last_update TIMESTAMP NOT NULL,
  name VARCHAR(255) NOT NULL
);






